import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/dashboard/header";
import { Toaster } from "react-hot-toast";
import { AdminJapanSidebar } from "@/components/dashboard/admin-sidebar-japan";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Car Inventory",
	description: "Generated by create next app",
};

export default function JapanLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
			<Toaster />
			<div className="flex h-screen">
				<AdminJapanSidebar />
				<div className="flex flex-1 flex-col">
					<Header />
					{children}
				</div>
			</div>
		</div>
	);
}
